pierwsza linijka master
druga linijka branch1
trzecia linijka master
czwarta linijka master
piąta linijka branch2
szósta linijka master
siódma linijka master
ósma linijka master
dziewiąta linijka master
dziesiąta linijka master
